apiVersion: v1
kind: Service
metadata:
  name: react-todo-service
spec:
  type: NodePort
  selector:
    app: react-todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
